### ISSUE TITLE
Don't panic if Discord is not running

### ISSUE THREAD

**Issue by d4rckh** [vionya/discord-rich-presence#34]
When Discord is not running the crate panics:
```rust
thread 'main' panicked at C:\Users\andrei\.cargo\registry\src\index.crates.io-6f17d22bba15001f\discord-rich-presence-0.2.4\src\ipc_windows.rs:60:43:  
Client not connected
```
my code is just this:
```rust
    let mut client = DiscordIpcClient::new("1258151270234198096").unwrap();
    
    let _ = client.connect();
    
    let _ = client.set_activity(activity::Activity::new()
        .state("with the money machine")
        .details("Making money")
    );     
```

Allow us to completly ignore the fact that discord is not running and handle the error by us.

**Comment by Bowarc** [comment]
The panic is due to a call of `self.send_handshake()?;` which calls `self.send` which calls `self.write`
In that write method, on windows and unix, the 'socket' is `.expect`ed.

There is error handling, just missing that case :p

I'll see if i can push a quick patch
