### ISSUE TITLE
Clear Request After Reconnect Doesn't Work

### ISSUE THREAD

**Issue by FelixSiegel** [vionya/discord-rich-presence#43]
**Problem**  
After reconnecting to the IPC gateway, I am unable to clear my current presence using the `clear_activity` method. This occurs if I attempt to reconnect before sending the clear request. Here's the code that reproduces the issue:

```rust
use discord_rich_presence::{activity, DiscordIpc, DiscordIpcClient};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut client = DiscordIpcClient::new("1076049094281277531")?;
    client.connect()?;

    let payload = activity::Activity::new().state("Test");
    client.set_activity(payload)?;

    client.close()?;
    client.reconnect()?;

    std::thread::sleep(std::time::Duration::from_secs(5));

    client.clear_activity()?;

    client.close()?;
    Ok(())
}
```

**Expected Behavior**  
The presence should be cleared when calling `clear_activity` after reconnecting.

**Observed Behavior**  
While the presence is set correctly on initial connection, calling `clear_activity` after reconnecting does not clear it.

**Additional Information**  
- Operating System: Linux (`x86_64`)

Am I missing something in my implementation, or could this be a bug?

**Comment by Bowarc** [comment]
Could it be Discord's update rate?

Try sleeping a lot between `clear_activity` and `close`

**Comment by FelixSiegel** [comment]
Thank you very much, that actually worked! I will set the issue as closed. But I still have a question, maybe someone can help me :D 

Is there a way to keep the rpc alive even after the program has ended and to clear the rpc later by another program? Because as far as I've seen, the rpc is terminated as soon as you end the current program where you initialized it, even if I don't call the `close` method or if I set the PID to a constant value instead of the program's PID.

**Comment by Bowarc** [comment]
The reason the stream closes when you stop your program even tho `.close` is never called is because Files (on windows) and UnixStream on Linux / Mac(i believe mac uses theses too) auto-close on drop.

Even `Box::leak`ing it will probably get caught by your os and be closed.

The only way is to keep your program running.

**Comment by FelixSiegel** [comment]
Ok alright, that makes sense, thank you very much. I appriciate that fast and kind response :+1:
